# Generated by Django 3.0.8 on 2020-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(default='1994-11-23'),
            preserve_default=False,
        ),
    ]
